/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class android_backport_webp_WebPFactory */

#ifndef _Included_com_pl_webplibrary_BitmapFactory
#define _Included_com_pl_webplibrary_BitmapFactory
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_pl_webplibrary_BitmapFactory
 * Method:    nativeDecodeByteArray
 * Signature: ([BLandroid/graphics/BitmapFactory/Options;)Landroid/graphics/Bitmap;
 */
JNIEXPORT jobject JNICALL Java_com_pl_webplibrary_BitmapFactory_nativeDecodeByteArray
  (JNIEnv *, jclass, jbyteArray, jobject);

JNIEXPORT jobject JNICALL Java_com_pl_webplibrary_BitmapFactory_nativeDecodeFile
  (JNIEnv *jniEnv, jclass, jstring path, jobject options);


#ifdef __cplusplus
}
#endif
#endif
